var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/monitor/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0onkf0~._.js")
R.c("server/chunks/ssr/node_modules_0vtdjw7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_04~r-2v.js")
R.c("server/chunks/ssr/[root-of-the-server]__0i50yne._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/app_0brogi1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_monitor_page_actions_0h8x--h.js")
R.m(45592)
module.exports=R.m(45592).exports
