// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/audit" | "/code" | "/conversations" | "/coordination" | "/coordinator" | "/doutora-kitty" | "/files" | "/login" | "/memory-admin" | "/memory-graph" | "/monitor" | "/profile"
type AppRouteHandlerRoutes = "/api/agent/greeting" | "/api/agent/identity" | "/api/audit/logs" | "/api/auth/debug" | "/api/auth/login" | "/api/auth/me" | "/api/auth/profile" | "/api/chat/feedback" | "/api/chat/stream" | "/api/code/execute" | "/api/conversations" | "/api/conversations/[id]" | "/api/conversations/[id]/duplicate" | "/api/coordination/[...route]" | "/api/coordination/triage" | "/api/coordinator/tasks" | "/api/costs/breakdown/[userId]" | "/api/currency" | "/api/doutora-kitty/interpretation" | "/api/doutora-kitty/seed" | "/api/files/action" | "/api/files/download" | "/api/files/list" | "/api/files/raw" | "/api/files/read" | "/api/health" | "/api/memory/context/build" | "/api/memory/orchestrate" | "/api/memory/profile/compile" | "/api/memory/sync" | "/api/memory/users/[id]/audit" | "/api/memory/users/[id]/graph" | "/api/memory/users/[id]/items" | "/api/memory/users/[id]/items/[itemId]" | "/api/memory/users/[id]/profile" | "/api/monitor/stats" | "/api/ping" | "/api/plugins/list" | "/api/plugins/toggle" | "/api/search" | "/api/tools/status" | "/api/tools/toggle" | "/api/workflow" | "/api/workflow/seed" | "/api/workflow/status"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/agent/greeting": {}
  "/api/agent/identity": {}
  "/api/audit/logs": {}
  "/api/auth/debug": {}
  "/api/auth/login": {}
  "/api/auth/me": {}
  "/api/auth/profile": {}
  "/api/chat/feedback": {}
  "/api/chat/stream": {}
  "/api/code/execute": {}
  "/api/conversations": {}
  "/api/conversations/[id]": { "id": string; }
  "/api/conversations/[id]/duplicate": { "id": string; }
  "/api/coordination/[...route]": { "route": string[]; }
  "/api/coordination/triage": {}
  "/api/coordinator/tasks": {}
  "/api/costs/breakdown/[userId]": { "userId": string; }
  "/api/currency": {}
  "/api/doutora-kitty/interpretation": {}
  "/api/doutora-kitty/seed": {}
  "/api/files/action": {}
  "/api/files/download": {}
  "/api/files/list": {}
  "/api/files/raw": {}
  "/api/files/read": {}
  "/api/health": {}
  "/api/memory/context/build": {}
  "/api/memory/orchestrate": {}
  "/api/memory/profile/compile": {}
  "/api/memory/sync": {}
  "/api/memory/users/[id]/audit": { "id": string; }
  "/api/memory/users/[id]/graph": { "id": string; }
  "/api/memory/users/[id]/items": { "id": string; }
  "/api/memory/users/[id]/items/[itemId]": { "id": string; "itemId": string; }
  "/api/memory/users/[id]/profile": { "id": string; }
  "/api/monitor/stats": {}
  "/api/ping": {}
  "/api/plugins/list": {}
  "/api/plugins/toggle": {}
  "/api/search": {}
  "/api/tools/status": {}
  "/api/tools/toggle": {}
  "/api/workflow": {}
  "/api/workflow/seed": {}
  "/api/workflow/status": {}
  "/audit": {}
  "/code": {}
  "/conversations": {}
  "/coordination": {}
  "/coordinator": {}
  "/doutora-kitty": {}
  "/files": {}
  "/login": {}
  "/memory-admin": {}
  "/memory-graph": {}
  "/monitor": {}
  "/profile": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
