// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit">> = Specific
  const handler = {} as typeof import("../../app/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/code/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/code">> = Specific
  const handler = {} as typeof import("../../app/code/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/conversations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/conversations">> = Specific
  const handler = {} as typeof import("../../app/conversations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/coordination/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coordination">> = Specific
  const handler = {} as typeof import("../../app/coordination/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/coordinator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coordinator">> = Specific
  const handler = {} as typeof import("../../app/coordinator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/doutora-kitty/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doutora-kitty">> = Specific
  const handler = {} as typeof import("../../app/doutora-kitty/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/files/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/files">> = Specific
  const handler = {} as typeof import("../../app/files/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/memory-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/memory-admin">> = Specific
  const handler = {} as typeof import("../../app/memory-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/memory-graph/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/memory-graph">> = Specific
  const handler = {} as typeof import("../../app/memory-graph/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/monitor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitor">> = Specific
  const handler = {} as typeof import("../../app/monitor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent/greeting/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/greeting">> = Specific
  const handler = {} as typeof import("../../app/api/agent/greeting/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent/identity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/identity">> = Specific
  const handler = {} as typeof import("../../app/api/agent/identity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/logs">> = Specific
  const handler = {} as typeof import("../../app/api/audit/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/debug">> = Specific
  const handler = {} as typeof import("../../app/api/auth/debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/profile">> = Specific
  const handler = {} as typeof import("../../app/api/auth/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chat/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/feedback">> = Specific
  const handler = {} as typeof import("../../app/api/chat/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chat/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/stream">> = Specific
  const handler = {} as typeof import("../../app/api/chat/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/code/execute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/code/execute">> = Specific
  const handler = {} as typeof import("../../app/api/code/execute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/conversations/[id]/duplicate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversations/[id]/duplicate">> = Specific
  const handler = {} as typeof import("../../app/api/conversations/[id]/duplicate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/conversations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversations/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/conversations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/conversations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversations">> = Specific
  const handler = {} as typeof import("../../app/api/conversations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/coordination/[...route]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coordination/[...route]">> = Specific
  const handler = {} as typeof import("../../app/api/coordination/[...route]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/coordination/triage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coordination/triage">> = Specific
  const handler = {} as typeof import("../../app/api/coordination/triage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/coordinator/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coordinator/tasks">> = Specific
  const handler = {} as typeof import("../../app/api/coordinator/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/costs/breakdown/[userId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/costs/breakdown/[userId]">> = Specific
  const handler = {} as typeof import("../../app/api/costs/breakdown/[userId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/currency/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/currency">> = Specific
  const handler = {} as typeof import("../../app/api/currency/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/doutora-kitty/interpretation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/doutora-kitty/interpretation">> = Specific
  const handler = {} as typeof import("../../app/api/doutora-kitty/interpretation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/doutora-kitty/seed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/doutora-kitty/seed">> = Specific
  const handler = {} as typeof import("../../app/api/doutora-kitty/seed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/files/action/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/files/action">> = Specific
  const handler = {} as typeof import("../../app/api/files/action/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/files/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/files/download">> = Specific
  const handler = {} as typeof import("../../app/api/files/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/files/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/files/list">> = Specific
  const handler = {} as typeof import("../../app/api/files/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/files/raw/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/files/raw">> = Specific
  const handler = {} as typeof import("../../app/api/files/raw/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/files/read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/files/read">> = Specific
  const handler = {} as typeof import("../../app/api/files/read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/memory/context/build/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory/context/build">> = Specific
  const handler = {} as typeof import("../../app/api/memory/context/build/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/memory/orchestrate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory/orchestrate">> = Specific
  const handler = {} as typeof import("../../app/api/memory/orchestrate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/memory/profile/compile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory/profile/compile">> = Specific
  const handler = {} as typeof import("../../app/api/memory/profile/compile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/memory/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory/sync">> = Specific
  const handler = {} as typeof import("../../app/api/memory/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/memory/users/[id]/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory/users/[id]/audit">> = Specific
  const handler = {} as typeof import("../../app/api/memory/users/[id]/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/memory/users/[id]/graph/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory/users/[id]/graph">> = Specific
  const handler = {} as typeof import("../../app/api/memory/users/[id]/graph/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/memory/users/[id]/items/[itemId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory/users/[id]/items/[itemId]">> = Specific
  const handler = {} as typeof import("../../app/api/memory/users/[id]/items/[itemId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/memory/users/[id]/items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory/users/[id]/items">> = Specific
  const handler = {} as typeof import("../../app/api/memory/users/[id]/items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/memory/users/[id]/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory/users/[id]/profile">> = Specific
  const handler = {} as typeof import("../../app/api/memory/users/[id]/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/monitor/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitor/stats">> = Specific
  const handler = {} as typeof import("../../app/api/monitor/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ping/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ping">> = Specific
  const handler = {} as typeof import("../../app/api/ping/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/plugins/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plugins/list">> = Specific
  const handler = {} as typeof import("../../app/api/plugins/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/plugins/toggle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plugins/toggle">> = Specific
  const handler = {} as typeof import("../../app/api/plugins/toggle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tools/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tools/status">> = Specific
  const handler = {} as typeof import("../../app/api/tools/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tools/toggle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tools/toggle">> = Specific
  const handler = {} as typeof import("../../app/api/tools/toggle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/workflow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workflow">> = Specific
  const handler = {} as typeof import("../../app/api/workflow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/workflow/seed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workflow/seed">> = Specific
  const handler = {} as typeof import("../../app/api/workflow/seed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/workflow/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workflow/status">> = Specific
  const handler = {} as typeof import("../../app/api/workflow/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
