var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/memory-graph/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0.tu8wn._.js")
R.c("server/chunks/ssr/node_modules_0vtdjw7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0-a-7-u.js")
R.c("server/chunks/ssr/[root-of-the-server]__0i50yne._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/app_0brogi1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_memory-graph_page_actions_0_x.v1n.js")
R.m(79706)
module.exports=R.m(79706).exports
